BOOTSTRAP_SERVER=localhost:9092
CONSUMER_TOPIC=autoobile_raw_diagnostics
PRODUCER_TOPIC=automobile_processed_diagnostics
ERROR_TOPIC=automobile_failures
CONSUMER_GROUP=Consumer_Automobile
POSTGRES_URI=jdbc:postgresql://localhost:5432/
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=postgres123
DB_TABLE=automobile_diagnostic_new
BATCH_SIZE=500
LINGER_MS=20000
